### ISSUE TITLE
Positive set coordinate discordance with ucsc ESTs

### ISSUE THREAD

**Issue by ngiangre** [ngiangre/HMMicro#10]
There's a bit over 100 miRNA sites from the positive set that don't overlap hg19 ESTs from the ucsc table browser. Should we throw those away? From the table browser: assembly hg19, group mRNA and EST, track human mRNAs, table human ESTs (all est). Are some sites denoting binding to pre-mRNA?

**Comment by flw88** [comment]
I'd probably want to hold onto them. We can try both w/ or w/out. I think it's possible that the liftover wasn't perfect we can do some spotchecks. It's also possible that sites are binding to pre-mRNA (as you suggested :) )

**Comment by flw88** [comment]
Did some spot checks, they seem to be alright. We can reopen this if it seems it might be an issue.
