### ISSUE TITLE
Find State Distributions

### ISSUE THREAD

**Issue by ngiangre** [ngiangre/HMMicro#11]
For use in Pomegranate, we need to assign each state (e.g, binding/non-binding) a distribution. Essentially bin the chromosome and count the number of sites in each bin to get a histogram. Then test for following a common distribution family

**Comment by ngiangre** [comment]
see findingStateDistributions ntbk in Scripts/Python. Let me know your thoughts if you think this is thinking in the right direction. We can talk about it later but you think you @flw88 can use a similar distribution in pomegranate?

**Comment by flw88** [comment]
I'll take a look, Nick.

**Comment by flw88** [comment]
Thanks again for getting this started, Nick. I'm a bit confused by the quantile stuff you've got going. What are you trying to define?

**Comment by ngiangre** [comment]
Maybe quantile isn't the right term-what I mean is I tried to bin chromosome 22 but instead of giving the actual bases I turned them into a fraction. I asked how many start sites are bw x-5% and x% of chr22. You can change that to whatever makes more sense.

**Comment by ngiangre** [comment]
I updated this script-I found an example online that goes through all known common distributions to find the best fit. Then I try to express it in a form that pomegranate can use but I think this should be tweaked. But I think what's laid out in the notebook should be a great start for training. Let me know if I should do anything else for this.
