### ISSUE TITLE
Downloading more data

### ISSUE THREAD

**Issue by ngiangre** [ngiangre/HMMicro#4]
DeepBlueR doesn't contain all the HEK293 data from ENCODE so I'll need to get the BigWig files directly from the ftp site and incorporate into the matrix. This should be done simultaneously with HMM learning or put as second priority to HMM learning.

**Comment by ngiangre** [comment]
There's only 1 more signal file we can use and get-a DNase experiment from ENCODE. Let me get that and include it in the matrix. I'll have it done by Saturday morning hopefully but it's not going to inhibit our learning process we just might have to train the HMM again if we train it before I add this.

**Comment by flw88** [comment]
That's fine. Having an iterative process should work well.

**Comment by ngiangre** [comment]
Can't download the chr1 data from the DeepBlue server. Seems like a lost cause unfortunately...
