### ISSUE TITLE
HMM training with Pomegranate

### ISSUE THREAD

**Issue by ngiangre** [ngiangre/HMMicro#5]
Open issue for our progress.

**Comment by ngiangre** [comment]
@flw88, want to give this a stab?

**Comment by flw88** [comment]
Yeah, let me put some work into it. Hope to have something by Saturday

**Comment by ngiangre** [comment]
I've been looking over your scripts. I'm trying to think about what the reduced matrix we generated represents. Seems like it will be used as our emission matrix? And our states right now are binding/nonbinding so we need to learn the transition matrix? I'm kinda unclear on this, wanna sit down and go over it?

**Comment by flw88** [comment]
Yeah, let's work on it later this weekend. I'm unfortunately slammed with work right now (lots of experiments)

**Comment by ngiangre** [comment]
No worries, yeah this weekend sounds good! I'll think about this during the week

**Comment by ngiangre** [comment]
done
