### ISSUE TITLE
Executing dimReduce.py locally

### ISSUE THREAD

**Issue by flw88** [ngiangre/HMMicro#8]
Nick, is the reason `dimReduce.py` didn't work locally for you perhaps because `file` is a defined python type?

**Comment by ngiangre** [comment]
I get this error

Nicholass-MacBook-Pro-2:HMMicro nickgiangreco$ Scripts/Python/dimReduce.py 
Traceback (most recent call last):
  File "Scripts/Python/dimReduce.py", line 14, in <module>
    from sklearn.decomposition import PCA
ImportError: No module named 'sklearn'

I can import these modules fine in the ipython notebooks. Is it ipython or jupyter notebooks?
