### ISSUE TITLE
Generating negative set

### ISSUE THREAD

**Issue by ngiangre** [ngiangre/HMMicro#9]
I'm working on getting a negative miRNA binding set. Using bedtools shuffle, I'll get coordinates of genomic fragments with the same length distribution as the positive set from within hg19.

This file 'Hafner.combined_AGO.proc.start.end.hg19.bed' is the positive set correct?

 I will make sure sampling is from (-incl parameter) coding regions (Should it be only 3' UTRs or all UTRs or just human mRNAs (track from ucsc under assembly hg19 and group 'mRNA and EST'? Want to suggest a track?) , 

excludes the positive set regions, 

samples start sites uniformly among chromosomes (-chromFirst parameter; this takes away bias for larger chromosomes-is this ok?),

and generates fragments that don't overlap with each other (-noOverlapping parameter).

**Comment by ngiangre** [comment]
I was looking at why the bedtools shuffle command was taking so long to complete, and I figured out one of my parameters was inhibiting the whole process (including human ESTs in sampled sites). Here's my command:

bedtools shuffle -i ~/GitHub/HMMicro/CLIP_data/HEK293/Hafner.combined_AGO.proc.start.end.hg19.bed -g Annot/hg19/hg19.chrom.sizes.txt -chrom -noOverlapping -excl ~/GitHub/HMMicro/CLIP_data/HEK293/Hafner.combined_AGO.proc.start.end.hg19.bed > ~/GitHub/HMMicro/data/negative_set.bed

So the negative set excludes regions from the positive set, they don't overlap and the sites are from the same chromosome. This should be good. Let me know if you have any objections.

**Comment by flw88** [comment]
Positive set: Hafner.combined_AGO.proc.hg19.bed

**Comment by ngiangre** [comment]
I updated the negative set to the above correct positive set. The command used was: 

bedtools shuffle -i ~/GitHub/HMMicro/CLIP_data/HEK293/Hafner.combined_AGO.proc.hg19.bed -g ~/Documents/Columbia/Courses/COMPUTATIONAL_GENOMICS/HMMicro_notgit/Annot/hg19/hg19.chrom.sizes.txt -chrom -noOverlapping -excl ~/GitHub/HMMicro/CLIP_data/HEK293/Hafner.combined_AGO.proc.hg19.bed > ~/GitHub/HMMicro/data/negative_set.bed

Reopen the issue if we need to do more work with this
